package com.gs.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class FirstServlet extends HttpServlet {

	private static final long serialVersionUID = -3857662232662066892L;

	@Override
	protected void service(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		PrintWriter out = res.getWriter();
		out.print("<html>");
		out.print("<head><title>first servlet</title></head>");
		out.print("<body><div style='color:green;border:1px silver solid;'>It's a page which generated by servlet!</div></body>");
		out.print("</html>");
		out.close();
	}

}
